### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by yanhongyan419** [ireneperezsalesa/event_tracking#1]
Hello, is there a way to obtain the datasets used in the project? Is it self-labeled or public?

**Comment by ireneperezsalesa** [comment]
Hello!

For the neural networks, we have used pretrained models of E2VID and YOLO that are publicly available (links to both can be found in the readme file). As for testing the tracker on event data, we have found useful the example datasets linked in the E2VID repository, as well as the VisEvent dataset which is available here: https://github.com/wangxiao5791509/VisEvent_SOT_Benchmark

I hope this helps!
